"""Part management tools for Windchill MCP Server."""

from __future__ import annotations

import json

from windchill.odata.filter import F
from windchill.odata.query import Query

from windchill_mcp.server import get_client, mcp


@mcp.tool()
async def windchill_search_parts(
    filter_expr: str | None = None,
    select: str | None = None,
    top: int = 50,
    latest_version: bool = True,
) -> str:
    """Search for parts in Windchill PLM.

    Args:
        filter_expr: OData filter expression (e.g. "contains(Name,'bracket')",
            "Source eq 'MAKE'", "State eq 'RELEASED'"). Supports standard OData
            operators: eq, ne, gt, lt, contains, startswith, endswith, and/or.
        select: Comma-separated list of properties to return
            (e.g. "ID,Name,Number,State,Source").
        top: Maximum number of results to return (default 50).
        latest_version: If true, return only the latest version of each part.

    Returns:
        JSON array of matching parts with their properties.
    """
    try:
        client = await get_client()
        query = Query().top(top)
        if latest_version:
            query = query.latest_version()
        if filter_expr:
            query = query.filter(F.raw(filter_expr))
        if select:
            query = query.select(*[s.strip() for s in select.split(",")])
        result = await client.prod_mgmt.list_parts(query)
        return json.dumps(result.items, indent=2, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def windchill_get_part(part_id: str) -> str:
    """Get detailed information about a specific part.

    Args:
        part_id: The Object Reference ID of the part.

    Returns:
        JSON object with all part properties including Name, Number, State,
        Version, Source, DefaultUnit, and more.
    """
    try:
        client = await get_client()
        result = await client.prod_mgmt.get_part(part_id)
        return json.dumps(result, indent=2, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def windchill_create_part(
    name: str,
    number: str | None = None,
    context_id: str | None = None,
    source: str | None = None,
) -> str:
    """Create a new part in Windchill.

    Args:
        name: Part name (required).
        number: Part number. Auto-generated by Windchill if omitted.
        context_id: Container Object Reference ID to create the part in.
            Use windchill_list_containers to find available containers.
        source: Part source type - "MAKE", "BUY", or "MAKE_OR_BUY".

    Returns:
        JSON object of the newly created part.
    """
    try:
        client = await get_client()
        result = await client.prod_mgmt.create_part(
            name,
            number=number,
            context_id=context_id,
            source=source,
        )
        return json.dumps(result, indent=2, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def windchill_checkout_part(part_id: str) -> str:
    """Check out a part for editing. Returns the working copy.

    The part must not already be checked out. After editing, use
    windchill_checkin_part with the working copy ID to check it back in.

    Args:
        part_id: The Object Reference ID of the part to check out.

    Returns:
        JSON object of the working copy (use its ID for checkin).
    """
    try:
        client = await get_client()
        result = await client.prod_mgmt.checkout_part(part_id)
        return json.dumps(result, indent=2, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def windchill_checkin_part(
    working_copy_id: str,
    comment: str | None = None,
) -> str:
    """Check in a part working copy after editing.

    Args:
        working_copy_id: The Object Reference ID of the working copy
            (returned from windchill_checkout_part).
        comment: Optional checkin comment describing the changes.

    Returns:
        JSON object of the checked-in part.
    """
    try:
        client = await get_client()
        result = await client.prod_mgmt.checkin_part(
            working_copy_id, comment=comment
        )
        return json.dumps(result, indent=2, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def windchill_revise_part(part_id: str) -> str:
    """Create a new revision of a part.

    This creates a new version letter (e.g., A -> B) for the part.
    The part must be in a checked-in state.

    Args:
        part_id: The Object Reference ID of the part to revise.

    Returns:
        JSON object of the new revision.
    """
    try:
        client = await get_client()
        result = await client.prod_mgmt.revise_part(part_id)
        return json.dumps(result, indent=2, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def windchill_set_part_state(part_id: str, state: str) -> str:
    """Set the lifecycle state of a part.

    Common states: INWORK, UNDERREVIEW, RELEASED, CANCELLED.
    The state transition must be valid per the part's lifecycle template.

    Args:
        part_id: The Object Reference ID of the part.
        state: Target lifecycle state name (e.g. "RELEASED", "INWORK").

    Returns:
        JSON object confirming the state change.
    """
    try:
        client = await get_client()
        result = await client.prod_mgmt.set_part_state(part_id, state)
        return json.dumps(result, indent=2, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def windchill_get_bom(part_id: str, levels: int = 1) -> str:
    """Get the Bill of Materials (BOM) for a part.

    Returns the child components/materials used by this part.

    Args:
        part_id: The Object Reference ID of the parent part.
        levels: Number of BOM levels to retrieve (1 = immediate children only).
            Use 1 for single-level BOM. For multi-level, use
            windchill_get_part_structure instead.

    Returns:
        JSON array of BOM line items (part usage links).
    """
    try:
        client = await get_client()
        if levels > 1:
            result = await client.prod_mgmt.get_part_structure(part_id)
            return json.dumps(result, indent=2, default=str)
        result = await client.prod_mgmt.get_bom(part_id)
        return json.dumps(result.items, indent=2, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def windchill_get_where_used(part_id: str) -> str:
    """Find all parent assemblies that use a given part.

    This is the reverse of BOM lookup - it answers "where is this part used?"

    Args:
        part_id: The Object Reference ID of the part.

    Returns:
        JSON array of parent assemblies that reference this part.
    """
    try:
        client = await get_client()
        result = await client.prod_mgmt.get_where_used(part_id)
        return json.dumps(result, indent=2, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def windchill_download_part_content(
    part_number: str,
    output_path: str | None = None,
) -> str:
    """Download the primary document/file associated with a part.

    Looks up the part by number, finds its linked document via the
    DescribedBy relationship, and downloads the primary content (e.g., PDF).

    Args:
        part_number: The part number (e.g., "WH806239").
        output_path: Optional file path to save to. If not provided,
            uses the original filename in the current directory.

    Returns:
        JSON with the download result including file path and size.
    """
    try:
        client = await get_client()

        # Find the part by number
        parts = await client.prod_mgmt.list_parts(
            Query().filter(F.eq("Number", part_number)).top(1).latest_version()
        )
        if not parts.items:
            return json.dumps({"error": f"Part {part_number} not found"})

        part = parts.first
        part_id = part["ID"]

        # Get content info
        content_info = await client.prod_mgmt.get_part_content_info(part_id)
        if not content_info:
            return json.dumps({"error": f"No downloadable content found for part {part_number}"})

        # Download
        saved_path = await client.prod_mgmt.download_part_content(part_id, output_path)

        return json.dumps({
            "success": True,
            "part_number": part_number,
            "file_name": content_info.file_name,
            "file_size": content_info.file_size,
            "format": content_info.format,
            "saved_to": saved_path,
        }, indent=2)
    except Exception as e:
        return json.dumps({"error": str(e)})
